/**
 * Verdict — single calm paragraph rendering the verdict copy.
 *
 * Spec ref:
 *   - docs/spec.md > Frontend > components/Verdict.tsx
 *   - docs/prd.md > Reading the Verdict > US-3
 *
 * Server component. The text comes from `profile.verdict`, generated by
 * lib/summary.ts with deterministic worst-3 ranking + hedge-word linter.
 * One paragraph, max-prose width, calm typography.
 */
type Props = {text: string};

export default function Verdict({text}: Props) {
  return (
    <div className="max-w-prose mx-auto">
      <p className="text-base leading-relaxed text-gray-800">{text}</p>
    </div>
  );
}
